/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(modals)'}/mission-settings` | `/mission-settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(modals)'}/practice-settings` | `/practice-settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(modals)'}/translator-history` | `/translator-history`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/discover` | `/discover`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/practice` | `/practice`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/reader` | `/reader`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/translator` | `/translator`; params?: Router.UnknownInputParams; } | { pathname: `/auth/callback`; params?: Router.UnknownInputParams; } | { pathname: `/tasks/audioCacheTask`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/sign-in`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(modals)'}/mission-settings` | `/mission-settings`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(modals)'}/practice-settings` | `/practice-settings`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(modals)'}/translator-history` | `/translator-history`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/discover` | `/discover`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/practice` | `/practice`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/reader` | `/reader`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/translator` | `/translator`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/callback`; params?: Router.UnknownOutputParams; } | { pathname: `/tasks/audioCacheTask`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/sign-in${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(modals)'}/mission-settings${`?${string}` | `#${string}` | ''}` | `/mission-settings${`?${string}` | `#${string}` | ''}` | `${'/(modals)'}/practice-settings${`?${string}` | `#${string}` | ''}` | `/practice-settings${`?${string}` | `#${string}` | ''}` | `${'/(modals)'}/translator-history${`?${string}` | `#${string}` | ''}` | `/translator-history${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/discover${`?${string}` | `#${string}` | ''}` | `/discover${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/practice${`?${string}` | `#${string}` | ''}` | `/practice${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/reader${`?${string}` | `#${string}` | ''}` | `/reader${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/translator${`?${string}` | `#${string}` | ''}` | `/translator${`?${string}` | `#${string}` | ''}` | `/auth/callback${`?${string}` | `#${string}` | ''}` | `/tasks/audioCacheTask${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(modals)'}/mission-settings` | `/mission-settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(modals)'}/practice-settings` | `/practice-settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(modals)'}/translator-history` | `/translator-history`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/discover` | `/discover`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/practice` | `/practice`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/reader` | `/reader`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/translator` | `/translator`; params?: Router.UnknownInputParams; } | { pathname: `/auth/callback`; params?: Router.UnknownInputParams; } | { pathname: `/tasks/audioCacheTask`; params?: Router.UnknownInputParams; };
    }
  }
}
